In [4]:
import numpy as np
a=np.array([20,40,50,70,10])
b=np.array([6,2,9,7,1])
print(a)
print(b)
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[20 40 50 70 10]
[6 2 9 7 1]
[26 42 59 77 11]
[14 38 41 63  9]
[120  80 450 490  10]
[ 3.33333333 20.          5.55555556 10.         10.        ]


In [5]:
import numpy as np
a=np.array([20,40,50,70,10])
b=np.array([6,2,9,7,1])
print(a.dot(b))
scl=3
print("Scalar Value:",scl)
print("Array:",a)
print("Result:",a*scl)


1150
Scalar Value: 3
Array: [20 40 50 70 10]
Result: [ 60 120 150 210  30]


In [7]:
import numpy as np
a=np.array([[10,20],[30,40]])
b=np.array([[3,7],[5,9]])
print(a%b)

[[1 6]
 [0 4]]


In [10]:
def my_fun(x,y):
    if x>y:
        return x-y
    else:
        return x+y
a1=[10,7,2]
a2=[6,7,3]
v=np.vectorize(my_fun)
print("Array1:",a1)
print("Array2:",a2)
print("Result:",v(a1,a2))

Array1: [10, 7, 2]
Array2: [6, 7, 3]
Result: [ 4 14  5]
