In [2]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9])
s1=a[2:6]
print(s1)

[3 4 5 6]


In [3]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9])
s2=a[::2]
print(s2)

[1 3 5 7 9]


In [4]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9])
s3=a[::-1]
print(s3)

[9 8 7 6 5 4 3 2 1]


In [5]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
s=a[0:2,1:3]
print(s)

[[2 3]
 [5 6]]


In [6]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
s=a[::1,0:2]
print(s)

[[1 2]
 [4 5]
 [7 8]]


In [7]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
s=a[:2,:1]
print(s)

[[1]
 [4]]


In [8]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
s=a[:,0]
print(s)

[1 4]


In [9]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
s=a[0,:]
print(s)

[1 2 3]


In [12]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
s=a[0:3:2]
print(s)

[[1 2 3]
 [7 8 9]]


In [17]:
import numpy as np
import array
a=array.array('i',[1,2,3,4,5])
print(a[0])
print(a[-1])

1
5


In [21]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a[0,0])

1


In [20]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a[2:5])

[3 4 5]


In [31]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a[0,1])

2


In [29]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a[a>2])

[3 4 5]


In [30]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a[[1,3]])

[2 4]


In [4]:
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
r=np.hstack((a,b))
print(r)

[[1 2 5 6]
 [3 4 7 8]]


In [5]:
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
r=np.vstack((a,b))
print(r)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [7]:
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
r=np.dstack((a,b))
print(r)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [8]:
import numpy as np
a=np.array([1,2,3,4,5,6])
r=np.split(a,3)
print(r)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [10]:
import numpy as np
a=np.array([1,2,3,4,5])
r=np.array_split(a,3)
print(r)

[array([1, 2]), array([3, 4]), array([5])]
