In [1]:
import numpy as np
a=np.array([1,2,3])
print("\nOne dimensional array:\n",a)


One dimensional array:
 [1 2 3]


In [2]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print("\nTwo dimensional array:\n",a)



Two dimensional array:
 [[1 2 3]
 [4 5 6]]


In [3]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("\nThree dimensional array:\n",a)


Three dimensional array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
import numpy as np
a=np.zeros((3,4))
print("\nArray withinall zeros:\n",a)


Array withinall zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
import numpy as np
a=np.random.random((3,4))
print("\nRandom values:\n",a)


Random values:
 [[0.35272793 0.3531686  0.37021817 0.65192567]
 [0.02460406 0.07800071 0.2983611  0.50512155]
 [0.37554711 0.38352275 0.26447955 0.96227533]]


In [6]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
b=a.reshape((3,4))
print("\nOriginal array:\n",a)
print("\nReshaped array:\n",b)


Original array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Reshaped array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [7]:
import numpy as np
a=np.arange(0,51,5)
print("\nSequence array:\n",a)


Sequence array:
 [ 0  5 10 15 20 25 30 35 40 45 50]


In [8]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=a.flatten()
print("\nOriginal array:\n",a)
print("\nFlatten array:\n",b)


Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Flatten array:
 [1 2 3 4 5 6 7 8 9]


In [16]:
import numpy as np
a=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print("\nNo of dimensions:\n",a.ndim)


No of dimensions:
 3


In [19]:
import numpy as np
a=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print("\nShape of array:\n",a.shape)


Shape of array:
 (2, 2, 3)


In [21]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print("\nArray element:",a.dtype)


Array element: int64


In [24]:
import numpy as np
a=np.array([1,2,3,4,5,6])
l=len(a)
print("\nLenght of the array:",l)


Lenght of the array: 6


In [2]:
import numpy as np
a=[1,2,3]
a=np.array(a)
n=a.astype('float64')
print(n)
print(n.dtype)

[1. 2. 3.]
float64
