In [1]:
import numpy as np
a=np.array([1,6,2,7,6,4])
x=np.where(a==6)
print(x)

(array([1, 4]),)


In [2]:
import numpy as np
a=np.array([1,6,2,7,6,4])
x=np.where(a==7)
print(x)

(array([3]),)


In [4]:
import numpy as np
a=np.array([1,6,2,7,6,4])
x=np.where(a%2==0)
print(x)

(array([1, 2, 4, 5]),)


In [5]:
import numpy as np
a=np.array([1,6,2,7,6,4])
x=np.where(a%3==1)
print(x)

(array([0, 3, 5]),)


In [7]:
import numpy as np
a=np.array([0,1,2,2,7,8,9])
x=np.searchsorted(a,8,side='left')
print(x)

5


In [10]:
import numpy as np
a=np.array([0,1,2,2,7,8,9])
x=np.searchsorted(a,3,side='right')
print(x)

4


In [11]:
import numpy as np
a=np.array([9,5,2,7,6,4])
print(np.sort(a))

[2 4 5 6 7 9]


In [12]:
import numpy as np
a=np.array([4,7,2,9,5,3,4])
print(np.sort(a))

[2 3 4 4 5 7 9]


In [14]:
import numpy as np
a=np.array([[7,4,9],[9,1,4]])
print(np.sort(a))

[[4 7 9]
 [1 4 9]]


In [15]:
import numpy as np
a=np.array([31,78,69,100])
x=[False,True,False,True]
n=a[x]
print(x)
print(n)

[False, True, False, True]
[ 78 100]


In [16]:
import numpy as np
a=np.array([1,2,3,4])
x=[True,True,True,True]
n=a[x]
print(n)

[1 2 3 4]


In [18]:
import numpy as np
a=np.array([31,78,69,100])
f=a>70
n=a[f]
print(f)
print(n)

[False  True False  True]
[ 78 100]
